services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instaclone_app
    restart: unless-stopped
    workdir_dir: /var/www
    volumes:
    - .:/var/www
    depends_on:
      - db
    networks:
      - instaclone

nginx:
  image: ngix:alpine
  container_name: instaclone_nginx
  restart: unless-stopped
  ports:
    - "8000:80"
  volumes:
    - .:/var/www 
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  depends_on:
    - app
  networks:
    -instaclone

  db:
    image: mysql:8.0
    container_name: instaclone_db
    restart: unless-stopped
    ports:
      -"3307:3306"
    enviroment:
      MYSQL_DATABASE : insta_clone
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: laravel
      MYSQL_USER: dev
    volumes:
      -dbdata:/var/lib/mysql
    networks:
      -instaclone

volumes:
  dbdata:

networks:
  instaclone:
    drive: bridge